
#SCREEN 
SCREEN_WIDTH = 900
SCREEN_HEIGHT = 600
SCREEN_COLOR = "white"

#DROP DOWN MENU CONSTANTS 
DROP_DOWN_FONT_SIZE = 30
LIST_OF_ALGORITHMS = ["Bubble Sort" , "Insertion Sort" , "Selection Sort" , "Quick Sort" , "Merge Sort"]
DROPDOWN_HOVER_COLOR = "black"
DROPDOWN_TEXT_COLOR = (100,33,55)
DROPDOWN_COORDINATES = (50,25)
DROPDOWN_BOX_COLOR = (200,200,200)
DROP_DOWN_WIDTH  = 170
DROP_DOWN_HEIGHT = 37

#LIST
ELEMENT_SPACING = 5 
ARRAY = [0,0,0,0,0,0,0,0,0,0]
LIST_FONT_SIZE = 36
LIST_WIDTH = 60 # width of each element 
LIST_HEIGHT = 40 # height of each element 
LIST_BACKGROUND_COLOR = "white"
LIST_TEXT_COLOR = "black"
LIST_BOARDER_COLOR = "black"
LIST_CORDINATES = (220,100)


#GENERATE ARRAY BUTTON

GEN_ARR_FONT_SIZE = 20
GEN_ARR_COORDINATES = (50,100)
GEN_ARR_HEIGHT = 40 
GEN_ARR_WIDTH = 150 
GEN_ARR_TEXT  = "Generate Array"
GEN_ARR_TEXT_COLOR = "black"
GEN_ARR_BG_COLOR = (100, 200, 255)